config/routes.rb
Rails.application.routes.draw do

  root 'statics#index'

  get    'about',   to: 'statics#about'
  get    'contact', to: 'statics#contact'
  get    'signup',  to: 'users#new'
  get    'login',   to: 'sessions#new'
  post   'login',   to: 'sessions#create'
  delete 'logout',   to: 'sessions#destroy'

  resources :users

end

app/models/follow.rb
class Follow < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :liker, class_name: "User"
  belongs_to :liked, class_name: "Post"
  validates :liker_id, presence: true
  validates :liked_id, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :content, presence: :true, length: { minimum: 4, maximum: 50 }
	validates :title, presence: :true, length: { maximum: 150 }
	validates :description, length: { maximum: 2000 }



	default_scope -> { order('created_at DESC') }

	#relationships
	belongs_to :user, dependent: :destroy

  has_many :likes, foreign_key: "liked_id", dependent: :destroy
  has_many :liking_users, :through => :likes, source: :liker
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  
  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  validates :bio, length: { maximum: 2000 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                          format: { with: VALID_EMAIL_REGEX },
                          uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  
  #relationships
	has_many :posts, dependent: :destroy

	has_many :likes, foreign_key: "liker_id", dependent: :destroy
	has_many :liked_posts, through: :likes, source: :liked

	has_many :follows, foreign_key: "follower_id", dependent: :destroy
	has_many :followed_users, through: :follows, source: :followed

  # Returns the hash digest of the given string
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if !!(user && user.authenticate(params[:session][:password]))
  		# Log the user in and redirect to user's show page.
  		log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
  		redirect_back_or user
  	else
  		# Create an error that they can see.
  		flash.now[:danger] = "Invalid email/password combination."
  		render 'new'
  	end
  end

  def destroy
  	log_out if logged_in?
  	redirect_to root_url
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to BeatRoot!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def show
  	@user = User.find(params[:id])
  end

  def update
    if @user.update_attributes(user_params)
      # Handle successful updates.
      flash[:success] = "Profile updated"
      redirect_to @user

    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password,
                                     :password_confirmation)
    end

    # Before filters

    # Confirms a logged in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in to see this page."
        redirect_to login_url
      end
    end

    # Confirms correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# Logs the user in by setting up a temp session.
	def log_in(user)
		session[:user_id] = user.id
	end

	# Remembers a user in a persistent session
	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	# Returns true if the current user is the user asked for.
	def current_user?(user)
		user == current_user
	end

	# Returns the current user.
	def current_user
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			if user && user.authenticated?(cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
	end

	# Checks if a user is logged in.
	def logged_in?
		!current_user.nil?
	end

	#Forgets a persisten session.
	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

	# Redirects to stored location or back
	def redirect_back_or(default)
		redirect_to(session[:forwarding_url] || default)
		session.delete(:forwarding_url)
	end

	# Stores location to help friendly forwarding.
	def store_location
		session[:forwarding_url] = request.url if request.get?
	end
end

app/helpers/statics_helper.rb
module StaticsHelper
	def full_title(name = '')
		base_title = "BeatRoot"
		if name.empty?
			return base_title
		else
			return name + " | " + base_title
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.first_name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="/">BeatRoot</a>
	</small>
	<nav>
		<ul>
			<li><%= link_to "Contact", contact_url %> </li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "BeatRoot", root_url, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_url %> </li>
				<li><%= link_to "About", about_url %> </li>
				<% if logged_in? %>
					<li><%= link_to "Users", users_path %></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Account <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Profile", current_user %></li>
							<li><%= link_to "Settings", edit_user_path(current_user) %></li>
							<li class="divider"></li>
							<li>
								<%= link_to "Log out", logout_path, method: "delete" %>
							</li>
						</ul>	
					</li>
				<% else %>
					<li><%= link_to "Log in", login_path %> </li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |message_type, message| %>
			<div class="alert alert-<%= message_type %>">
				<%= message %>
			</div>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>	
		<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/statics/about.html.erb
<% provide(:title, "About") %>
<h1>About BeatRoot</h1>
<div class="col-xs-offset-1" class="col-xs-10">
	<p>BeatRoot is an application made for people who
	love making music, and want other input on the
	music that they make.</p>
</div>

app/views/statics/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>This is the contact page.</p>

app/views/statics/index.html.erb
<% provide(:title, "Home") %>

<div class="center jumbotron">

<h1>Welcome to BeatRoot</h1>

<h2>Listen and share your music!</h2>

<%= link_to "Sign Up!", signup_path, class: "btn btn-lg btn-danger" %> 
<p>This is the home page for the application</p>

</div>

<!-- Put logo here -->

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size: 50 %>
	<%= link_to user.first_name + " " + user.last_name, user %>
	<% if current_user.admin? && !current_user?(user) %>
		| <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?"} %>
	<% end %>
</li>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
 <% provide(:title, 'Edit User') %>
<h1>Update your profile</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">

	<%= form_for(@user) do |f| %>

	  <%= render 'shared/error_messages' %>

	  <%= f.label :first_name %>
	  <%= f.text_field :first_name, class: "form-control" %>

	  <%= f.label :last_name %>
	  <%= f.text_field :last_name, class: "form-control" %>

	  <%= f.label :email %>
	  <%= f.text_field :email, class: "form-control" %>

	  <%= f.label :password %>
	  <%= f.password_field :password, class: "form-control" %>

	  <%= f.label :password_confirmation, "Confirm Password" %>
	  <%= f.password_field :password_confirmation, class: "form-control" %>

	  <%= f.submit "Save changes", class: "btn btn-primary" %>

	<% end %>
	
	<div class="gravatar_edit">
		<%= gravatar_for @user %>
		<a href="http://gravatar.com/emails" target="_blank">change</a>
	</div>
	</div>

</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1>All Users</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign up</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">

	<%= form_for(@user) do |f| %>

	  <%= render 'shared/error_messages' %>

	  <%= f.label :first_name %>
	  <%= f.text_field :first_name, class: "form-control" %>

	  <%= f.label :last_name %>
	  <%= f.text_field :last_name, class: "form-control" %>

	  <%= f.label :email %>
	  <%= f.text_field :email, class: "form-control" %>

	  <%= f.label :password %>
	  <%= f.password_field :password, class: "form-control" %>

	  <%= f.label :password_confirmation, "Confirm Password" %>
	  <%= f.password_field :password_confirmation, class: "form-control" %>

	  <%= f.submit "Create my Account", class: "btn btn-primary" %>

	<% end %>

	</div>

</div>

app/views/users/show.html.erb
<% provide(:title, @user.first_name) %>

<h1>
	<%= gravatar_for @user %>
	<%= @user.first_name %> <%= @user.last_name %>
</h1>